version: '3.9'

services:
  postgres_db:
    image: postgres:15.0-alpine
    ports:
      - '5431:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

